name: Deploy to AWS EC2 Virta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Build Docker Image
        run: |
          sudo docker-compose build laravel.test
        env:
          WWWGROUP: '1000'
          WWWUSER: '1000'
          PWD: ${{ github.workspace }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a0s1s2l1

      - name: Push Docker Image to Amazon ECR
        run: |
          docker tag virta-app:latest public.ecr.aws/a0s1s2l1/virta-app:latest

      - name: Deploy to AWS EC2 via AWS Systems Manager Run Command
        run: |
          docker push public.ecr.aws/a0s1s2l1/virta-app:latest
